[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
# The primary colors for the terminal window
background = '#0d1b2a'
foreground = '#e0e1dd'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.normal]
# Normal colors used by applications
black = '#0d1b2a'
red = '#8d5aa6'
green = '#06a77d'
yellow = '#f77f00'
blue = '#4ea5d9'
magenta = '#8d5aa6'
cyan = '#71c7ec'
white = '#e0e1dd'

[colors.bright]
# Bright colors used for emphasis
black = '#415a77'
red = '#8d5aa6'
green = '#06a77d'
yellow = '#f77f00'
blue = '#71c7ec'
magenta = '#8d5aa6'
cyan = '#71c7ec'
white = '#e0e1dd'
